name: Node CI

on:
  push:
    branches:
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests - Lint and Test
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: cd lib/unit-tests
        run: cd lib/unit-tests
      - name: Install
        run: yarn install
        env:
          CI: true
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
